on:
  workflow_dispatch:

jobs:
  secret-generator:
    environment: production
    runs-on: ubuntu-latest
    steps:
    - name: use secret
      shell: bash
      run: |
        echo "hello world"
    - name: use variables
      run: |
        echo "repository variable : $REPOSITORY_VAR"
      env:
        REPOSITORY_VAR: ${{ github.ref == 'refs/heads/main' && vars.REPOSITORY_VAR || vars.OVERRIDE_VAR }}
        
