on:
  workflow_dispatch:

jobs:
  secret-generator:
    environment: production
    runs-on: ubuntu-latest
    steps:
    - name: use secret
      shell: bash
      run: |
        echo "hello world"
    - shell: bash
      env:
        SUPER_SECRET: ${{ secrets.test }}
      run: |
         echo "$SUPER_SECRET"
